Source.py function signatures
USEPA/flowsa pull request #150
Opened 2021-12-15 13:12 UTC by matthewlchambers

This represents an extensive refactoring of `flowbyactivity.py` and every `source.py` file except `elciFBS.py` and `stewiFBS.py`, with the goals of:

1. Allowing/supporting better use of the `.yaml` method files in generating FBAs
2. Greater flexibility/robustness to future design decisions
3. Greater transparency in reading code and easier bug-squashing

To address these goals, this PR implements the following across _all_ `source.py` files:

1. The functions identified as `url_replace_fxn`, `call_response_fxn`, and `parse_response_fxn` now accept _only_ keyword arguments (see corollary below). This removes the need to stick to a particular order for passing arguments to these functions, and eliminates the situation where a couple of (classes of) functions had the same parameters in a different order. 
2. These functions (`url_replace_`, `call_response_`, and `parse_response_`) now accept any number of keyword arguments. This has two implications: first, these functions can now list only the set of argument that they actually need (goals 2 and 3), and second, if future design decisions or data sources imply that additional arguments should be passed by `flowbyactivity.py` to some subset of these functions, the others don't need to be modified at all.
3. These functions now list precisely the set of arguments they actually need, promoting goals 2 and 3. The one caveat to this is that the information from the `.yaml` file is passed as the single dictionary `config`, because breaking it down further seems unfeasible, given the generalized nature of the `.yaml` files.
4. The `args` dictionary is no longer used.

This PR implements the following changes in the `flowbyactivity.py` file:

1. Corollary to 1, above: The `url_replace_`, `call_response_`, and `parse_response_` functions are now provided with all arguments as keyword arguments.
2. The `assemble_urls_for_query`, `call_urls`, `parse_data`, and `process_data_frame` functions in `flowbyactivity.py` (which dynamically import and call the functions discussed above), now accept only keyword arguments and are therefore called with keyword arguments.
3. The `config` dictionary, containing information from the `.yaml` file, is passed to all the above functions (so it is now available to any of the `url_replace_`, `call_response_`, and `parse_response_` functions if needed).
4. The `build_url_for_query` function has been folded into `assemble_urls_for_query`.

I've tested the code from this PR by generating a full set of FBAs, except that I was not able to generate FBAs for the Blackhurst, Census, BLM, StatCan, or USDA data for other reasons (lack of the `tabula` Python package for Blackhurst and BLM, lack of API key for Census and USDA, and the StatCan website being down). I was also not able to generate FBAs for USGS Gallium, Zeolites, and NWIS, for reasons which I believe are not connected to this refactoring (issues reading excel files for Gallium and Zeolites, and an `IndexError` somewhere in the body of the `usgs_call` function for NWIS).

2021-12-16 21:10 UTC, bl-young requested changes
This looks good to me pending a few minor comments above. Thanks @matthewlchambers this is much clearer

I did not review each of the data source scripts in detail.

2021-12-16 21:41 UTC, matthewlchambers commented on flowsa/flowbyactivity.py
> +    if (urlinfo := config['url']) == 'None':
That would, now that you mention it. I can make it more verbose again. And I'll try to keep the 3.7 compatibility goal in mind.

2021-12-16 21:45 UTC, matthewlchambers commented on flowsa/flowbyactivity.py
> +        build_url = build_url.replace("__year__", str(year))
All of this is true. I was mostly trying to leave the old code alone on this pass.

2021-12-16 21:46 UTC, matthewlchambers commented on flowsa/flowbyactivity.py
>      replace parts of the url string
I'll get that fixed, thanks!

2021-12-16 22:08 UTC, matthewlchambers commented on flowsa/flowbyactivity.py
> +        build_url = build_url.replace("__year__", str(year))
If you'd like me to change it, though, I can.

2021-12-16 23:48 UTC, bl-young commented on flowsa/flowbyactivity.py
> +        build_url = build_url.replace("__year__", str(year))
if you don't mind making that quick change. I don't want to do it on develop so as to cause a conflict

2021-12-17 18:08 UTC, matthewlchambers commented on flowsa/flowbyactivity.py
> +        build_url = build_url.replace("__year__", str(year))
Done!

2021-12-17 18:12 UTC, bl-young approved these changes

2021-12-20 14:18 UTC, catherinebirney commented
Thanks @matthewlchambers, we've tried a few different methods of parameter input naming conventions to `url_replace_`, `call_response_`, and `parse_response_` - your modifications make these functions easier to follow

2021-12-20 14:19 UTC, merged