enable multiple `inherits_from` in fbs method
USEPA/flowsa pull request #199
Opened 2022-04-06 01:40 UTC by bl-young

uses [dpath](https://pypi.org/project/dpath/) for better accessing and manipulating of dictionaries in order to support `inherits_from` at different nodes in FBS method.

For [example](https://github.com/WesIngwersen/GHGbyindustrydocs/commit/b33a3dec3209096ac13d6c66885cebae2d3ad901):
```
inherits_from: BEA_summary_target
target_geoscale: national
source_names:
  inherits_from: GHG_national_2016_m1
```

Using inherits from in an FBS method will update the method from the target identified at that specific node. In the example above, everything within `source_names` from `GHG_national_2016_m1` is added to this method. No further adjustments of this node are possible.

This PR also ensures that inherits_from can use target methods within local directory (first) before looking for the target method in the repo. In the example above prevents the need to have a local version of `BEA_summary_target` when generating FBS outside the repo.

Existing use of `inherits_from` in FBA methods are not impacted.

2022-04-06 01:43 UTC, bl-young commented
fyi @WesIngwersen I tested the [example summary method](https://github.com/WesIngwersen/GHGbyindustrydocs/commit/b33a3dec3209096ac13d6c66885cebae2d3ad901) above and the results at a glance seem to match the totals of the detailed model

2022-04-06 12:06 UTC, catherinebirney approved these changes

2022-04-06 17:59 UTC, matthewlchambers commented
Does this change the order of precedence? That is, does the parent now override the child, rather than the other way around?

2022-04-06 18:09 UTC, bl-young commented
> Does this change the order of precedence? That is, does the parent now override the child, rather than the other way around?

I think it will, which may not be desired. There may be a way to rearrange that. It certainly would be nice if we could keep any data at that node from the child and not have all the parent override it. Something like the following (which I don't think is correct FBS method, but would allow for revising the year while keeping everything else from the parent)
```
inherits_from: BEA_summary_target
target_geoscale: national
source_names:
  year: 2018
  inherits_from: GHG_national_2016_m1
```
I'm open to other ideas to implement this.

2022-04-06 21:12 UTC, matthewlchambers commented
I'll think about it. I've been looking into custom `yaml` tags and constructors anyway, so maybe something along those lines will work. Just to make sure I understand correctly, the goal is for us to be able to inherit a particular node from another file, at any level of the tree?

2022-04-07 13:44 UTC, bl-young commented
> Just to make sure I understand correctly, the goal is for us to be able to inherit a particular node from another file, at any level of the tree?

Correct. And to ensure that we can inherit from more than one file.

2022-04-11 21:43 UTC, matthewlchambers commented
See my implementation in #200. It would require some refactoring of existing `yaml` files, but I think it incorporates the best features of both my previous implementation and this one, as well as making further changes in the future easier.

2022-04-11 21:48 UTC, matthewlchambers requested changes
See my proposed alternate implementation in https://github.com/USEPA/flowsa/pull/200. It would require some refactoring of existing `yaml` files, but I think it incorporates the best features of both my previous implementation and this one, as well as making further changes in the future easier.

2022-04-12 14:23 UTC, bl-young commented
closing in favor of #200

2022-04-12 14:23 UTC, closed without merging